# Generated by Django 2.1.5 on 2019-09-07 14:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import saleor.order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0078_auto_20190907_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='suborder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=386),
        ),
        migrations.AddField(
            model_name='suborder',
            name='customer_phone',
            field=saleor.order.models.PossiblePhoneNumberField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='suborder',
            name='payment_status',
            field=models.CharField(choices=[('refunded', 'refunded'), ('pending', 'pending'), ('sent', 'sent')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='suborder',
            name='ref_number',
            field=models.CharField(blank=True, max_length=386, validators=[django.core.validators.RegexValidator('^(A-Fa-f0-9)+$', message='Not a Valid Mpesa Reference Number')]),
        ),
        migrations.AddField(
            model_name='suborder',
            name='shop_name',
            field=models.CharField(blank=True, max_length=386),
        ),
        migrations.AddField(
            model_name='suborder',
            name='shop_phone',
            field=saleor.order.models.PossiblePhoneNumberField(blank=True, default='', max_length=128),
        ),
    ]
